(source "melpa" "http://melpa.milkbox.net/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "better-defaults")
(depends-on "color-theme-solarized")
(depends-on "fiplr")
(depends-on "flymake-cursor")
(depends-on "git-gutter-fringe")
(depends-on "grizzl")
(depends-on "guide-key")
(depends-on "highlight-indentation")
(depends-on "magit")
(depends-on "pallet")
(depends-on "project-explorer")
(depends-on "projectile")
(depends-on "rainbow-mode")
(depends-on "smart-mode-line")
(depends-on "smex")
(depends-on "web-mode")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "zenburn-theme")